#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#


language: python

python:
  - 3.6

services: sqlite3

env:
  - DJANGO=1.10.5

before_install:
  - export DJANGO_SETTINGS_MODULE=Diplomatool.settings
  - export PYTHONPATH=$HOME/builds/olety/Diplomatool
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:

script:
  - python manage.py test